package com.hoan.pagingexcel.common.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;


@JsonFormat(shape = JsonFormat.Shape.OBJECT)
@Getter
@AllArgsConstructor
public enum MenuStructureCode {
    EXPORT(MenuCodeVO.builder()
            .menuIdx(0)
            .menuId("export")
            .menuTitle("수출정보관리")
            .pathPrefix("/admin/export")
            .children(Arrays.asList(
                    MenuSubCodeVO.builder()
                            .index(0)
                            .parentMenuId("export")
                            .menuId("statistics")
                            .menuTitle("수출통계 및 현황")
                            .url("/admin/export/statistics")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(1)
                            .parentMenuId("export")
                            .menuId("examples")
                            .menuTitle("수출사례")
                            .url("/admin/export/examples")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(2)
                            .parentMenuId("export")
                            .menuId("world-its-market-infos")
                            .menuTitle("국가별 ITS 시장정보")
                            .url("/admin/export/world-its-market-infos")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(3)
                            .parentMenuId("export")
                            .menuId("its-order-infos")
                            .menuTitle("ITS 발주 정보")
                            .url("/admin/export/its-order-infos")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(4)
                            .parentMenuId("export")
                            .menuId("world-company-infos")
                            .menuTitle("해외 기업 소개")
                            .url("/admin/export/world-company-infos")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(5)
                            .parentMenuId("export")
                            .menuId("world-organization-infos")
                            .menuTitle("해외 기관 소개")
                            .url("/admin/export/world-organization-infos")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(6)
                            .parentMenuId("export")
                            .menuId("tech-market-trends")
                            .menuTitle("기술 시장 동향")
                            .url("/admin/export/tech-market-trends")
                            .build()
            ))
            .build()),
    EVENT(MenuCodeVO.builder()
            .menuIdx(1)
            .menuId("event")
            .menuTitle("행사정보관리")
            .pathPrefix("/admin/event")
            .children(Arrays.asList(
                    MenuSubCodeVO.builder()
                            .index(0)
                            .parentMenuId("event")
                            .menuId("road-show")
                            .menuTitle("로드쇼 안내")
                            .url("/admin/event/road-show")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(1)
                            .parentMenuId("event")
                            .menuId("training")
                            .menuTitle("초청연수 안내")
                            .url("/admin/event/training")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(2)
                            .parentMenuId("event")
                            .menuId("application")
                            .menuTitle("행사참가 신청")
                            .url("/admin/event/application")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(3)
                            .parentMenuId("event")
                            .menuId("gallery")
                            .menuTitle("갤러리")
                            .url("/admin/event/gallery")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(4)
                            .parentMenuId("event")
                            .menuId("schedule")
                            .menuTitle("전체 일정")
                            .url("/admin/event/schedule")
                            .build()
            ))
            .build()),
    PROMOTION(MenuCodeVO.builder()
            .menuIdx(2)
            .menuId("promotion")
            .menuTitle("홍보마당 관리")
            .pathPrefix("/admin/promotion")
            .children(Arrays.asList(
                    MenuSubCodeVO.builder()
                            .index(0)
                            .parentMenuId("promotion")
                            .menuId("videos")
                            .menuTitle("홍보영상")
                            .url("/admin/promotion/video")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(1)
                            .parentMenuId("promotion")
                            .menuId("brochures")
                            .menuTitle("브로슈어")
                            .url("/admin/promotion/brochure")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(2)
                            .parentMenuId("promotion")
                            .menuId("news-letters")
                            .menuTitle("뉴스레터")
                            .url("/admin/promotion/news-letter")
                            .build()
            ))
            .build()),
    LECTURE(MenuCodeVO.builder()
            .menuIdx(3)
            .menuId("education")
            .menuTitle("온라인 강의 관리")
            .pathPrefix("/admin/education")
            .children(Arrays.asList(
                    MenuSubCodeVO.builder()
                            .index(0)
                            .parentMenuId("education")
                            .menuId("online-lectures")
                            .menuTitle("온라인 강의")
                            .url("/admin/education/online-lectures")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(1)
                            .parentMenuId("education")
                            .menuId("library")
                            .menuTitle("자료실")
                            .url("/admin/education/library")
                            .build()
            ))
            .build()),
    COMMUNICATION(MenuCodeVO.builder()
            .menuIdx(4)
            .menuId("communication")
            .menuTitle("소통창구 관리")
            .pathPrefix("/admin/communication")
            .children(Arrays.asList(
                    MenuSubCodeVO.builder()
                            .index(0)
                            .parentMenuId("communication")
                            .menuId("notices")
                            .menuTitle("공지사항")
                            .url("/admin/communication/notices")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(1)
                            .parentMenuId("communication")
                            .menuId("survey")
                            .menuTitle("설문조사")
                            .url("/admin/communication/survey")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(2)
                            .parentMenuId("communication")
                            .menuId("board")
                            .menuTitle("수출상담게시판")
                            .url("/admin/communication/board")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(3)
                            .parentMenuId("communication")
                            .menuId("faq")
                            .menuTitle("FAQ")
                            .url("/admin/communication/faq")
                            .build()
            ))
            .build()),
    HOMEPAGE(MenuCodeVO.builder()
            .menuIdx(5)
            .menuId("homepage")
            .menuTitle("홈페이지 관리")
            .pathPrefix("/admin/homepage")
            .children(Arrays.asList(
                    MenuSubCodeVO.builder()
                            .index(0)
                            .parentMenuId("homepage")
                            .menuId("popups")
                            .menuTitle("팝업")
                            .url("/admin/homepage/popups")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(1)
                            .parentMenuId("homepage")
                            .menuId("banners")
                            .menuTitle("배너")
                            .url("/admin/homepage/banners")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(2)
                            .parentMenuId("homepage")
                            .menuId("contacts")
                            .menuTitle("문의처")
                            .url("/admin/homepage/contacts")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(3)
                            .parentMenuId("homepage")
                            .menuId("statistics")
                            .menuTitle("홈페이지 통계")
                            .url("/admin/homepage/statistics")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(4)
                            .parentMenuId("homepage")
                            .menuId("related-organization")
                            .menuTitle("유관기관 리스트")
                            .url("/admin/homepage/related-organization")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(5)
                            .parentMenuId("homepage")
                            .menuId("world-contact-info")
                            .menuTitle("해외연락망")
                            .url("/admin/homepage/world-contact-info")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(6)
                            .parentMenuId("homepage")
                            .menuId("domestic-contact-infos")
                            .menuTitle("국내연락망")
                            .url("/admin/homepage/domestic-contact-infos")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(7)
                            .parentMenuId("homepage")
                            .menuId("coworkers")
                            .menuTitle("협력 및 사업 리스트")
                            .url("/admin/homepage/coworkers")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(8)
                            .parentMenuId("homepage")
                            .menuId("center-members")
                            .menuTitle("센터 구성원 리스트")
                            .url("/admin/homepage/center-members")
                            .build()
            ))
            .build()),
    AUTH(MenuCodeVO.builder()
            .menuIdx(6)
            .menuId("auth")
            .menuTitle("사용자 관리")
            .pathPrefix("/admin/auth")
            .children(Arrays.asList(
                    MenuSubCodeVO.builder()
                            .index(0)
                            .parentMenuId("auth")
                            .menuId("user-info-collection")
                            .menuTitle("사용자 정보 수집 관리")
                            .url("/admin/auth/user-info-collection")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(1)
                            .parentMenuId("auth")
                            .menuId("admin-auths")
                            .menuTitle("관리자 접근권한 관리")
                            .url("/admin/auth/admin-auths")
                            .build()
            ))
            .build()),
    ONLINE_PROMOTION(MenuCodeVO.builder()
            .menuIdx(7)
            .menuId("auth")
            .menuTitle("온라인 홍보관 관리")
            .pathPrefix("/admin/online-promotion")
            .children(Arrays.asList(
                    MenuSubCodeVO.builder()
                            .index(0)
                            .parentMenuId("online-promotion")
                            .menuId("companies")
                            .menuTitle("기업소개")
                            .url("/admin/online-promotion/companies")
                            .build(),
                    MenuSubCodeVO.builder()
                            .index(1)
                            .parentMenuId("online-promotion")
                            .menuId("matchings")
                            .menuTitle("매칭신청")
                            .url("/admin/online-promotion/matchings")
                            .build()
            ))
            .build());

    private final MenuCodeVO menu;

}
